@startuml "Eco_Object"

class Eco_Object
class Eco_Object_Header
class Eco_Type
class Eco_Group
class Eco_Key

Eco_Object *-- Eco_Object_Header
Eco_Object *-- Eco_Type
Eco_Object : Eco_Object* next;
Eco_Object : Eco_Type* type;
Eco_Object : Eco_Object_Header header;
Eco_Object : void* Eco_Object_At(Eco_Object*, unsigned int);

Eco_Object_Header : unsigned int mark_queued : 1;
Eco_Object_Header : unsigned int mark_done : 1;


Eco_Type --|> Eco_Object
Eco_Type : Eco_Type_Shared* shared;
Eco_Type : unsigned int slot_count;
Eco_Type : Eco_Type_Slot slots[];

Eco_Group --|> Eco_Object
Eco_Group "1" o-- "1..*" Eco_Object
Eco_Group : unsigned int object_count;
Eco_Group : unsigned int object_alloc;
Eco_Group : Eco_Object** objects;

Eco_Key --|> Eco_Object
Eco_Key : Eco_Key* next;
Eco_Key : Eco_Key* prev;
Eco_Key : Eco_EConnect_Callback econnect_callback;
Eco_Key : char name[];

@enduml
