#ifndef ECO_BASE_CONFIG_H
#define ECO_BASE_CONFIG_H

#define ECO_NUMERIC_VERSION_STRING "0.1"

#ifdef ECO_LATEST_GIT_COMMIT
#  define ECO_VERSION_STRING ECO_NUMERIC_VERSION_STRING "-" ECO_LATEST_GIT_COMMIT
#else
#  define ECO_VERSION_STRING ECO_NUMERIC_VERSION_STRING
#endif

#define ECO_CONFIG_OS_TYPE_UNKNOWN 0
#define ECO_CONFIG_OS_TYPE_LINUX   1
#define ECO_CONFIG_OS_TYPE_FREEBSD 2
#define ECO_CONFIG_OS_TYPE_APPLE   3
#define ECO_CONFIG_OS_TYPE_WINDOWS 4

#ifdef __linux__
#  define ECO_CONFIG_TARGET_OS ECO_CONFIG_OS_TYPE_LINUX
#  define ECO_CONFIG_TARGET_LINUX
#  define ECO_CONFIG_UNIXLIKE
#else
# ifdef __FreeBSD__
#   define ECO_CONFIG_TARGET_OS ECO_CONFIG_OS_TYPE_FREEBSD
#   define ECO_CONFIG_UNIXLIKE
# else
#  ifdef __APPLE__
#    define ECO_CONFIG_TARGET_OS ECO_CONFIG_OS_TYPE_APPLE
#    define ECO_CONFIG_UNIXLIKE
#  else
#    ifdef _WIN32
#      define ECO_CONFIG_TARGET_OS ECO_CONFIG_OS_TYPE_WINDOWS
#      define ECO_CONFIG_WINDOWS
#    else
#      warning "Target OS could not be determined!"
#      define ECO_CONFIG_TARGET_OS ECO_CONFIG_OS_TYPE_UNKNOWN
#    endif
#  endif
# endif
#endif

#define ECO_CONFIG_USE_ANY_UINTPTR

#ifdef ECO_CONFIG_MAKEFILE_ENABLE_LIBZ
# define ECO_CONFIG_USE_ZLIB_COMPRESSION
#endif

#ifdef ECO_CONFIG_MAKEFILE_ENABLE_LIBFFI
# define ECO_CONFIG_USE_FFI
# define ECO_CONFIG_LIBFFI_INCLUDE <ffi.h>
#endif

#ifdef ECO_CONFIG_MAKEFILE_ENABLE_LIBDL
# define ECO_CONFIG_USE_DLOPEN
#endif

#ifdef ECO_CONFIG_TARGET_LINUX
# ifdef ECO_CONFIG_MAKEFILE_ENABLE_LIBDWARF
#  define ECO_CONFIG_USE_LIBDWARF
#  define ECO_CONFIG_LIBDWARF_INCLUDE1 <libdwarf/dwarf.h>
#  define ECO_CONFIG_LIBDWARF_INCLUDE2 <libdwarf/libdwarf.h>
# endif
#endif

#endif
